name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo "Hello world! welcome"
      - name: second step
        run: echo "Bye!"
  
